name: Central Docker Build and Push

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Show pushed ref
        run: |
          echo "Git ref is: $GITHUB_REF"

      - name: Extract tag name
        run: |
          TAG=${{ github.ref_name }}
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Show tag
        run: |
          echo "Tag is $TAG"

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ inputs.image_name }}:$TAG \
            -t ${{ inputs.image_name }}:latest \
      - name: Show built images
        run: |
          docker images | grep "${{ inputs.image_name }}"
            .
